repos:
  - repo: https://github.com/psf/black
    rev: '21.7b0' # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$
        language_version: python3 # Should be a command that runs python3.6+
  -   repo: https://github.com/pycqa/flake8
      rev: '3.9.2'  # pick a git hash / tag to point to
      hooks:
      -   id: flake8
          exclude: ^.*\b(migrations)\b.*$
          additional_dependencies: [flake8-bugbear==21.4.3]
          args:
            - "--max-line-length=88"
            - "--select=C,E,F,W,B,B950"
            - "--extend-ignore=E203,E501"