# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_legalaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='legal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
