# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 16:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('froide_legalaction', '0005_auto_20181018_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='plaintiff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='court_type',
            field=models.CharField(blank=True, choices=[('VG', 'Verwaltungsgericht'), ('OVG', 'Oberverwaltungsgericht'), ('BVerwG', 'Bundesverwaltungsgericht'), ('BVerfG', 'Bundesverfassungsgericht'), ('LVerfG', 'Landesverfassungsgericht'), ('EUG', 'Gericht der Europäischen Union'), ('EUGH', 'Europäischer Gerichtshof'), ('EMRK', 'European Court of Human Rights')], max_length=25),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='result',
            field=models.CharField(blank=True, choices=[('won', 'gewonnen'), ('lost', 'verloren'), ('not_accepted', 'nicht zur Entscheidung angenommen'), ('partially_successful', 'teilweise erfolgreich'), ('settled', 'Erledigung')], max_length=20),
        ),
    ]
