# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("froide_legalaction", "0006_auto_20181029_1730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawsuit",
            name="result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("won", "gewonnen"),
                    ("lost", "verloren"),
                    ("not_accepted", "nicht angenommen"),
                    ("partially_successful", "teilweise erfolgreich"),
                    ("settled", "Erledigung"),
                ],
                max_length=20,
            ),
        ),
    ]
