# Generated by Django 3.1.8 on 2021-06-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_legalaction', '0011_populate_instances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawsuit',
            name='court',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='court_type',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='start_date',
        ),
    ]
