# Generated by Django 4.0.7 on 2022-11-03 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0043_merge_20221019_1020'),
        ('froide_legalaction', '0014_auto_20220128_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldecision',
            name='foi_laws',
            field=models.ManyToManyField(related_name='legal_decisions', to='publicbody.foilaw'),
        )
    ]
