# Generated by Django 3.2.12 on 2022-02-15 14:41

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0039_publicbody_alternative_emails'),
        ('froide_legalaction', '0014_auto_20220128_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDecisionLaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_names', models.JSONField(default=list)),
                ('law_type', models.CharField(blank=True, max_length=255, verbose_name='law type')),
                ('foi_law', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicbody.foilaw')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='legaldecision',
            name='laws',
            field=models.ManyToManyField(blank=True, to='froide_legalaction.LegalDecisionLaw'),
        ),
        migrations.CreateModel(
            name='LegalDecisionLawTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='froide_legalaction.legaldecisionlaw')),
            ],
            options={
                'verbose_name': 'legal decision law Translation',
                'db_table': 'froide_legalaction_legaldecisionlaw_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
