# Generated by Django 4.2.1 on 2023-06-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "froide_legalaction",
            "0018_alter_instance_options_instance_decision_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="legaldecision",
            name="ecli",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="European Case Law Identifier",
            ),
        ),
        migrations.AddField(
            model_name="legaldecision",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
