# Generated by Django 4.2.1 on 2023-06-14 10:23

from django.conf import settings
from django.db import migrations
from django.utils import translation


def migrate_decision_type(apps, schema_editor):
    translation.activate(settings.LANGUAGE_CODE)
    LegalDecision = apps.get_model("froide_legalaction", "LegalDecision")
    for decision in LegalDecision.objects.filter(type__isnull=False):
        if decision.type.slug == "gerichtsbescheid":
            decision.decision_type = "court_notice"
        elif decision.type.slug == "urteil":
            decision.decision_type = "court_ruling"
        elif decision.type.slug == "beschluss":
            decision.decision_type = "court_decision"
        decision.save(update_fields=["decision_type"])


class Migration(migrations.Migration):
    dependencies = [
        ("froide_legalaction", "0020_legaldecision_decision_type_and_more"),
    ]

    operations = [migrations.RunPython(migrate_decision_type)]
