# Generated by Django 4.2.1 on 2023-06-14 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("froide_legalaction", "0021_auto_20230614_1223"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="legaldecisiontypetranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="legaldecisiontypetranslation",
            name="master",
        ),
        migrations.RemoveField(
            model_name="legaldecision",
            name="type",
        ),
        migrations.DeleteModel(
            name="LegalDecisionType",
        ),
        migrations.DeleteModel(
            name="LegalDecisionTypeTranslation",
        ),
    ]
