# Generated by Django 4.2.1 on 2023-06-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "froide_legalaction",
            "0022_alter_legaldecisiontypetranslation_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldecisiontranslation",
            name="fulltext",
            field=models.TextField(blank=True, verbose_name="Full text"),
        ),
    ]
