# Generated by Django 4.2.1 on 2023-06-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("froide_legalaction", "0023_alter_legaldecisiontranslation_fulltext"),
    ]

    operations = [
        migrations.AddField(
            model_name="legaldecisiontranslation",
            name="guiding_principle",
            field=models.TextField(blank=True, verbose_name="Guiding principle"),
        ),
        migrations.AlterField(
            model_name="legaldecision",
            name="decision_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("court_notice", "Court Notice"),
                    ("court_decision", "Court Decision"),
                    ("court_ruling", "Court Ruling"),
                    ("court_order", "Court Order"),
                ],
                max_length=20,
            ),
        ),
    ]
