# Generated by Django 4.2.1 on 2023-06-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "froide_legalaction",
            "0024_legaldecisiontranslation_guiding_principle_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="legaldecisiontranslation",
            name="title",
            field=models.CharField(blank=True, max_length=500, verbose_name="Title"),
        ),
    ]
