# Generated by Django 4.2.1 on 2023-06-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("froide_legalaction", "0025_legaldecisiontranslation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="legaldecision",
            name="source_url",
            field=models.URLField(blank=True, verbose_name="Source URL"),
        ),
    ]
