# Generated by Django 4.2.16 on 2025-01-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "froide_legalaction",
            "0027_legaldecision_created_at_legaldecision_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldecision",
            name="decision_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("court_decision", "Court Decision"),
                    ("court_ruling", "Court Ruling"),
                    ("court_order", "Court Order"),
                    ("court_notice", "Court Notice"),
                ],
                max_length=20,
                verbose_name="Decision Type",
            ),
        ),
        migrations.AlterField(
            model_name="legaldecision",
            name="reference",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="docket number"
            ),
        ),
    ]
